# Generated by Django 4.0.1 on 2022-01-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_rename_to_messagetouser_other_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetouser',
            name='other_email',
        ),
    ]
