# Generated by Django 4.0.1 on 2022-02-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_remove_messagetouser_other_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='choise',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=50, null=True, verbose_name='Habar holati'),
        ),
    ]
