# Generated by Django 4.0.1 on 2022-01-31 08:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('post', '0002_remove_posttranslation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
