# Generated by Django 4.0.1 on 2022-01-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_posttranslation_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttranslation',
            name='tags',
        ),
    ]
