# Generated by Django 4.0.1 on 2022-01-26 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('body', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='card_image/%Y/%m/%d/', verbose_name='Foto surat')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
